apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    {{- include "postgres.appLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432