apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprintometer
  labels:
    {{- include "sprintometer.appLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sprintometer.replicaCount }}
  selector:
    matchLabels:
      {{- include "sprintometer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sprintometer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: sprintometer
          image: {{ .Values.sprintometer.image.name }}:{{ .Values.sprintometer.image.tag }}
          ports:
            - name: tcp
              containerPort: 8080
          resources:
            limits:
              memory: {{ .Values.sprintometer.resources.limits.memory }}
              cpu: {{ .Values.sprintometer.resources.limits.cpu }}
            requests:
              memory: {{ .Values.sprintometer.resources.requests.memory }}
              cpu: {{ .Values.sprintometer.resources.requests.cpu }}